name: GitHubTahoeApp
options:
  bundleIdPrefix: com.Suryanshsaraf
  deploymentTarget:
    macOS: "14.0"

targets:
  GitHubTahoeApp:
    type: application
    platform: macOS
    sources:
      - path: GitHubTahoeApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.Suryanshsaraf.GitHubTahoeApp
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: U5277LWTD3
      CODE_SIGN_ENTITLEMENTS: GitHubTahoeApp/GitHubTahoeApp.entitlements
    info:
      path: GitHubTahoeApp/Info.plist
    dependencies:
      - target: GitHubTahoeWidget

  GitHubTahoeWidget:
    type: app-extension
    platform: macOS
    sources:
      - path: GitHubTahoeWidget
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.Suryanshsaraf.GitHubTahoeApp.WidgetExtension
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: U5277LWTD3
      CODE_SIGN_ENTITLEMENTS: GitHubTahoeWidget/GitHubTahoeWidget.entitlements
    info:
      path: GitHubTahoeWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
